test: Resolve build error after removal of CMSIS wrapper
[79%] Building C object interface/CMakeFiles/psa_api_ns.dir/src/tfm_ns_interface.o.
/data_sda/Workspace/mbed-os-tf-m-regression-tests/mbed-os/platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V1_1/TARGET_IGNORE/trusted-firmware-m/interface/src/tfm_ns_interface.c:12:10: fatal error: cmsis_os2.h: No such file or directory.
12 | #include "cmsis_os2.h".
compilation terminated..
interface/CMakeFiles/psa_api_ns.dir/build.make:146: recipe for target 'interface/CMakeFiles/psa_api_ns.dir/src/tfm_ns_interface.o' failed.
make[2]: *** [interface/CMakeFiles/psa_api_ns.dir/src/tfm_ns_interface.o] Error 1.
CMakeFiles/Makefile2:2398: recipe for target 'interface/CMakeFiles/psa_api_ns.dir/all' failed.
make[1]: *** [interface/CMakeFiles/psa_api_ns.dir/all] Error 2.
Makefile:148: recipe for target 'all' failed.